# server
server:
  port: 8046
  servlet:
    context-path: /

# spring

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qkdb?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html

  mvc:
    hiddenmethod:
      filter:
        enabled: false
#mybatis-plush配置
mybatis-plus:
  type-aliases-package: com.ca.pojo
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
# log
logging:
  level:
    com.cy: debug
  file:
    path: d:/dblogs/

#关于Dubbo配置
dubbo:
  scan:
    basePackages: com.ca    #指定dubbo的包路径
  application:              #应用名称
    name: provider-item     #一个接口对应一个服务名称
  registry:
    address: zookeeper://192.168.126.129:2181?backup=192.168.126.129:2182,192.168.126.129:2183
  protocol:  #指定协议
    name: dubbo  #使用dubbo协议(tcp-ip)  web-controller直接调用sso-Service
    port: 20881  #每一个服务都有自己特定的端口 不能重复.