# server
server:
  port: 8047
  servlet:
    context-path: /

# spring
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/qkdb?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    hiddenmethod:
      filter:
        enabled: false
mybatis-plus:
  type-aliases-package: com.ca.pojo
  mapper-locations: classpath:/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    com.cy: debug
  file:
    path: d:/dblogs/