# server
server:
  port: 8047
  servlet:
    context-path: /

# spring
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  mvc:
    hiddenmethod:
      filter:
        enabled: false


#配置dubbo消费者
dubbo:
  scan:
    basePackages: com.ca
  application:
    name: consumer-user   #定义消费者名称
  registry:               #注册中心地址
    address: zookeeper://192.168.126.129:2181?backup=192.168.126.129:2182,192.168.126.129:2183